version: '3'

services:
  go_tfe_api_wrapper:
    image: gotfeapiwrapper:1.0
    ports:
      - 8000:8000
    environment:
      AUTH_TOKEN: vtOrJJY0RH6BoA.atlasv1.gLu6Qq8DwzxZQ4Zj1TvzMPzffaqzlpAVpNPYPNyDxf2azm53N6hyQEjYr9NSaOD36WI
  waas_portal:
    image: waasportal
    stdin_open: true
    command: 'npm start'
    ports:
      - 3000:3000
    volumes:
      - ./waas_portal:/app
    depends_on:
      - go_tfe_api_wrapper
    links:
      - go_tfe_api_wrapper